### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by chocolateboy** [regexps/function-regex#2]
Various ES6 features are unsupported e.g.:
### test

``` javascript
var re = require('function-regex')();

var str1 = "function foo ({ bar, baz }) { }";
var str2 = "function foo ([ bar, baz ]) { }";
var str3 = "function foo (bar = 42) { }";
var str4 = "function foo (...bar) { }";

console.log(re.exec(str1));
console.log(re.exec(str2));
console.log(re.exec(str3));
console.log(re.exec(str4));
```
### output

```
null
null
null
null
```

**Comment by chocolateboy** [comment]
There's also `function*` (ES6) and `async function` (ES7).

**Comment by jonschlinkert** [comment]
IMHO this qualifies for a different regex. like `es6-function-regex`

**Comment by jonschlinkert** [comment]
technically this shouldn't even be called "function-regex" since it's not. It should be more specific, like: https://github.com/jonschlinkert/parse-code-context/blob/master/index.js#L14-L33

**Comment by chocolateboy** [comment]
> IMHO this qualifies for a different regex. like es6-function-regex

I agree that this is probably out of scope for this package.

But, come to think of it, a regex will never be able to handle destructured parameters in the general case, since regular languages don't support balanced delimiters.

**Comment by chocolateboy** [comment]
> https://github.com/jonschlinkert/parse-code-context/blob/master/index.js#L14-L33

FYI: that regex shares several issues with this regex and adds at least one new issue e.g. it doesn't handle:

``` javascript
function  foo () {} // > 1 space
```

or:

``` javascript
function // newline
foo () {}
```

**Comment by tunnckoCore** [comment]
Yea, I think it should go to something like `es6-function-regex` because we should also handle arrow functions?

**Comment by chocolateboy** [comment]
Closing this, since — as [mentioned](https://github.com/regexps/function-regex/issues/2#issuecomment-84482489) — a regex can't handle all ES6 function syntax (e.g. destructuring).
